// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_test

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcTestV2Client is the client API for GrpcTestV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcTestV2Client interface {
	Test(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type grpcTestV2Client struct {
	cc grpc.ClientConnInterface
}

func NewGrpcTestV2Client(cc grpc.ClientConnInterface) GrpcTestV2Client {
	return &grpcTestV2Client{cc}
}

func (c *grpcTestV2Client) Test(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc_test.v2.GrpcTestV2/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcTestV2Server is the server API for GrpcTestV2 service.
// All implementations must embed UnimplementedGrpcTestV2Server
// for forward compatibility
type GrpcTestV2Server interface {
	Test(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGrpcTestV2Server()
}

// UnimplementedGrpcTestV2Server must be embedded to have forward compatible implementations.
type UnimplementedGrpcTestV2Server struct {
}

func (UnimplementedGrpcTestV2Server) Test(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGrpcTestV2Server) mustEmbedUnimplementedGrpcTestV2Server() {}

// UnsafeGrpcTestV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcTestV2Server will
// result in compilation errors.
type UnsafeGrpcTestV2Server interface {
	mustEmbedUnimplementedGrpcTestV2Server()
}

func RegisterGrpcTestV2Server(s grpc.ServiceRegistrar, srv GrpcTestV2Server) {
	s.RegisterService(&GrpcTestV2_ServiceDesc, srv)
}

func _GrpcTestV2_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTestV2Server).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_test.v2.GrpcTestV2/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTestV2Server).Test(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcTestV2_ServiceDesc is the grpc.ServiceDesc for GrpcTestV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcTestV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_test.v2.GrpcTestV2",
	HandlerType: (*GrpcTestV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _GrpcTestV2_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_test_v2.proto",
}
